# Generated by Django 5.0.6 on 2025-07-02 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_checkin_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'date')},
        ),
    ]
