# Generated by Django 5.0.6 on 2025-07-03 03:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_checkin_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checkin',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.time(9, 2, 59, 878290)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='checkin_time',
        ),
    ]
