# Generated by Django 5.0.6 on 2025-07-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_checkin_unique_together_checkin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
